services:
  mysqlwp:
    container_name: wordpress_database
    image: mysql
    ports:
      - 3307:3306
    restart: always
    volumes:
      - C:/wordpressDocker/Wordpress_db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $SQL_ROOT_PWD
      MARIADB_USER: $SQL_USER
      MARIADB_PASSWORD: $SQL_PASSWD
      MARIADB_DATABASE: $SQL_DBNAME

  web:
    container_name: wordpress_www
    image: wordpress
    ports:
      - 81:80
    restart: always
    volumes:
      - C:/wordpressDocker/Wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysqlwp
      WORDPRESS_DB_USER: $SQL_USER
      WORDPRESS_DB_PASSWORD: $SQL_PASSWD
      WORDPRESS_DB_NAME: $SQL_DBNAME